<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>netiflux</AssemblyName>
    <RootNamespace>Netiflux</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" Version="2.4.17" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\themes.json" LogicalName="Netiflux.Resources.themes.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Netiflux.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Netiflux.Core\Netiflux.Core.csproj" />
  </ItemGroup>

</Project>
